### ISSUE TITLE
[Feature Request] possible UI improvements 

### ISSUE THREAD

**Issue by esmoak** [F4uzan/HgLauncher#11]
I wanted to suggest a few things that might improve HgLauncher. I can split these into separate issues if you want, and if you like the suggestions.

1.  ~~Ability to align app icons to right side of app panel (easier to touch with right hand). Maybe even a center alignment option~~  

**Edit:** Noted below that strike zone is whole row icon occupies and not just icon. 

2. Transparent app panel. 

3. I like how some launchers allow for creating separate app lists (see Search Based Launcher, or KISS with the tag groups). 

For example, the ability to have a "favorite apps" or "internet apps" list. If you felt like that would be a good fit for Hg, you could probably implement:

- long press an app to tag it with a custom list name. 
- Have a small bar above the app panel with toggles for list 1, 2, 3, etc. In fact, you could just make the list names as numbers and not let the user customize. 1 could be "all apps," 2 "favorites," or whatever the user chooses. 
- the bar could probably fit above or below the search in Hg, too, if the top doesn't seem feasible. 

I hesitated to submit this because I know you've already put a ton of work into this. And it shows since this launcher is already fantastic with a ton more potential. 

But I thought you might appreciate some input to help Hg distinguish itself from other launchers, to reach full potential. 

I do love this launcher, so thanks again.

**Comment by F4uzan** [comment]
I think some of these are a must, such as the tag/category system. I have some plans to implement it in the near future — probably for 1.4 — so I'll keep this issue open until I tackle that.

Regarding the 1 and 2, they seem to be easy enough to add. I'm not sure about 1's functionality though, as the app icon is only there for the sake of being there. Can you detail this, just in case I'm misinterpreting it in my side?

And please, don't hesitate! Ideas are always welcome here!

**Comment by F4uzan** [comment]
I'll consider it, though I don't like layout alterations that much, seeing that it tends to be largely unreliable and/or hard to maintain.

**Comment by esmoak** [comment]
I agree with you. I edited my original post. It's obviously up to if you want to still consider it, but I think your time would be better spent keeping the launcher lean, and focusing on more important things.

**Comment by F4uzan** [comment]
Shorthand has been implemented to satiate the third point. It should give users ability to curate the app list search results the way they want it. I suppose this implementation is good enough, but future issues are welcome to address its limitations.

As for transparent app panel/list, I may consider it for later releases. I'll be closing the issue as the biggest point here has been completed.
