### ISSUE TITLE
widget support

### ISSUE THREAD

**Issue by violoncelloCH** [F4uzan/HgLauncher#12]
Support for widgets on the main screen would be really cool!

**Comment by F4uzan** [comment]
An experimental widget support does exist! You can toggle it on by enabling testing mode (rapidly tap Settings -> About -> Version number). It's largely in the works, and widgets are anchored to the bottom to work around several issues it currently pose.

Other than all that, it's working fine if my tests are to be believed!

**Comment by violoncelloCH** [comment]
Wow cool, it works!
Is it planned to support multiple widgets (and adjustable size for them)?

**Comment by F4uzan** [comment]
All of those are planned for the near future, yes. They've been in my radar for far too long — and I'd like to get them done and implementated before 1.4. We'll see about that though!

**Comment by F4uzan** [comment]
Multiple widgets support should be up in v1.4! It's still severely limited, but it's much better than we have before. Closing this for a more specific issue later in the future.
