### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [F4uzan/HgLauncher#15]
Hi, I'm a logo designer, I saw your project and I can make a new free logo for your project. So, what do you think?

**Comment by F4uzan** [comment]
Sure thing! The current logo/icon is rather plain; a redesign may help it greatly — and any help is appreciated there.

**Comment by tebriz159** [comment]
I made a design. I combined H and G letters. If you like this, I'll send you original files.
![hglp](https://user-images.githubusercontent.com/31902754/52239537-90ff7b80-2883-11e9-93f8-ef4136f75ab1.png)
Which variation do you prefer? or which colors do you want?
![prhg](https://user-images.githubusercontent.com/31902754/52239694-f489a900-2883-11e9-8fd3-8ad1b4fdde3e.png)

**Comment by F4uzan** [comment]
That looks fantastic!

I can handle the background/mask shaping, as we'll be supporting adaptive icons here. If you may, I'll take the base (the logo, without the mask) so I can fit it in the launcher.

Regardless, thank you for your hard work and interest!

**Comment by tebriz159** [comment]
Sure, here's the files: https://drive.google.com/open?id=11GTc73Mgy1nhhfMVvnEMwtjz4z4wsajD
Please let me know when you use it )

**Comment by F4uzan** [comment]
Thank you! I'll tag you and this issue page in a commit to notify you.

**Comment by tebriz159** [comment]
Okay, thanks

**Comment by F4uzan** [comment]
The new icon design should be up in v1.4! Thank you once again to @tebriz159 for the generous contribution!
