### ISSUE TITLE
Swipe Up Gesture Non-functional

### ISSUE THREAD

**Issue by oneofmanyacdcfans** [F4uzan/HgLauncher#19]
The swipe up gesture does not work. I've tried setting it to different apps, and refreshing in the tap and hold menu but to no avail. 
My setup is HTC Desire 510 on 4.4.2.

**Comment by F4uzan** [comment]
Try swiping from the centre of the desktop. It's a tad finicky due to the launcher components competing for the swipe up motion, but in my side, it works out well if you swipe in the middle.

**Comment by F4uzan** [comment]
Try swiping from the centre of the desktop. It's a tad finicky due to the launcher components competing for the swipe up motion, but in my side, it works out well if you swipe in the middle.

**Comment by oneofmanyacdcfans** [comment]
You're right, that works. Just have to start at the middle of the screen.
