### ISSUE TITLE
[Feature required] show widget space with gesture

### ISSUE THREAD

**Issue by giupardeb** [F4uzan/HgLauncher#22]
I think that allow us to switch on widget space with a gesture (like right gesture) it's very important!

this launcher it's cool!

Thank you

**Comment by F4uzan** [comment]
This has been in my to-do list along with custom gesture actions. It'll definitely come in a future release!

**Comment by F4uzan** [comment]
This feature (as well as support for extended gesture actions) has been added by https://github.com/F4uzan/HgLauncher/commit/4ccbee2b6ef52ac6d1b6ad226092224e4e20f0ca. Closing this for now.
