### ISSUE TITLE
Error arrays xml

### ISSUE THREAD

**Issue by adam5525** [F4uzan/HgLauncher#23]
Cześć .Jak pisałem już wcześniej bawię się trochę edycją Twojego launchera.Twój plik arrays xml pokazuje błędy podczas kompilacji apk.Zmieniłem go trochę i kompiluje się bez problemu.

Problem mam tylko z pref_app_list_order_values...
Pozdrawiam i życzę przyjemnej pracy.

https://www7.zippyshare.com/v/9COpkMes/file.html

**Comment by F4uzan** [comment]
Thanks for the report!

Are you compiling using Android Studio? There shouldn't be any problem if you're using the latest version of Android Studio.
