### ISSUE TITLE
PopupMenu doesn't show in pinned apps

### ISSUE THREAD

**Issue by F4uzan** [F4uzan/HgLauncher#25]
**Collected from a report in Google Play Store.**

It seems that it is possible for PopupMenu/long-press menu to not show even though a long-press have been triggered (>1s event time). This may cause a wide array of issue, but most importantly, it disallows the user from unpinning an app.

The issue doesn't seem to stem from the number of apps pinned, which shows its disconnection from previous issues with pinned apps.

Other PopupMenu (or at least one in the app list items) works just fine. No regression is shown there.

The affected device so far is running Android 9.0 — no other report has been shown to indicate other versions are affected. I can't personally reproduce this myself, but further testing must be done to confirm that.

**Comment by grokkingnix** [comment]
Hi F4, thank you for this amazing app. It has everything I need. 

I have been having the same issue that's reported here. I have a list of apps in my favorites bar and I am unable to remove them by long pressing on them once they are in the favorites bar. 

I am using Android 10, In case you need additional information, please let me know and I'll do my best to get it for you.

**Comment by F4uzan** [comment]
Hi @grokkingnix, thank you for the kind words!

As of now, I can actually confirm the state of the issue (I'm affected by it as well!). I'll try to roll out a fix for this ASAP.
