### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath':

### ISSUE THREAD

**Issue by sherlockbeard** [F4uzan/HgLauncher#27]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :slidinguppanel:library.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :slidinguppanel:library.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :slidinguppanel:library.
Show Details
Affected Modules: app

Not sure how to properly build the project . i love this launcher i want to contribute. plz help and guide me .

**Comment by F4uzan** [comment]
Hi! Thanks for taking your time to report the issue.

This usually happens if the SlidingUpPanel library is not properly initialised. You can alternatively try cloning/downloading it from https://github.com/F4uzan/AndroidSlidingUpPanel and then placing it under the 'slidinguppanel' folder.

I may also need to know what you're compiling the launcher on. Is it the latest Android Studio?

**Comment by sherlockbeard** [comment]
thanks for replying . i did what you told me to do . but the error is still present .
and i am using  3.3.2 .

**Comment by F4uzan** [comment]
Can you check what contents 'slidinguppanel' have? This doesn't seem to be an Android Studio issue, so I presume that narrows down the issue a tad.

**Comment by sherlockbeard** [comment]
![Screenshot from 2019-04-02 18-30-19](https://user-images.githubusercontent.com/46790654/55404534-b522c480-5575-11e9-9a7a-f54e6abf2720.png)

**Comment by sherlockbeard** [comment]
this time zero sync error .
but while building i am getting this compile time error
![error](https://user-images.githubusercontent.com/46790654/55405177-1ac38080-5577-11e9-9aa5-5f8581b89b7a.png)

![libary](https://user-images.githubusercontent.com/46790654/55405204-2c0c8d00-5577-11e9-86da-b76437c0b3e8.png)

![depending](https://user-images.githubusercontent.com/46790654/55405215-2f077d80-5577-11e9-8bb1-251b5d3c73f6.png)

**Comment by F4uzan** [comment]
The structure of 'slidinguppanel' is wrong. Can you cut/move the contents of 'AndroidSlidingUpPanel' to 'slidinguppanel'? It seems that you have placed it incorrectly.

You shouldn't need to toy around the modules manually.

**Comment by sherlockbeard** [comment]
@F4uzan thank you . for helping.
the issue finally resolved it was a great debugging experience.
