### ISSUE TITLE
pulling down in main screen show the search box .

### ISSUE THREAD

**Issue by sherlockbeard** [F4uzan/HgLauncher#28]
puling down(when nothing is set as your default in slide down ) on the main . brings up the search box . 
![vlcsnap-2019-04-08-18h50m53s605](https://user-images.githubusercontent.com/46790654/55727332-6a9abf80-5a2f-11e9-8c05-b17857ff8a2e.png)

**Comment by F4uzan** [comment]
This is related to #19. Basically, the library used for handling the desktop view seems to have a trigger zone down below. Activating this trigger zone will cause the search bar to appear — and it can be activated by any vertical swipe.

A rework may be necessary on the library's side.

**Comment by sherlockbeard** [comment]
i tried experimenting a little 
if (newState == SlidingUpPanelLayout.PanelState.COLLAPSED
                        || newState == SlidingUpPanelLayout.PanelState.DRAGGING)

if i change it to   
if (newState == SlidingUpPanelLayout.PanelState.COLLAPSED)
then it don't show up anymore. but then search bar only show when the sliding or animation is completed.

**Comment by F4uzan** [comment]
I'll investigate it deeper on my side tomorrow. It may be a flubbed logic I can hack around to fix.

**Comment by sherlockbeard** [comment]
OK , is there any issue or anything in roadmap . that is good or easy for a beginner .

**Comment by sherlockbeard** [comment]
@F4uzan  list of installed app is not getting updated.
app installed after the installing this are not shown in launcher .

**Comment by F4uzan** [comment]
This (as well as a host of other gesture issues) has been fixed with 3d59327d879272419373483a01c1775a5f3a860d. I'll be closing this issue for the time being.
