### ISSUE TITLE
[Feature required] block auto-rotate display

### ISSUE THREAD

**Issue by giupardeb** [F4uzan/HgLauncher#32]
Can you add the option in HgLauncher settings menu that allow us to block rotate display when system auto-rotate display actived?

Thank you so much!

**Comment by F4uzan** [comment]
Sounds like a feature I'd use too. I'll queue it for the next release. Thanks for the suggestion!

**Comment by F4uzan** [comment]
Closing this as it has been implemented by https://github.com/F4uzan/HgLauncher/commit/fad556c404e2ba46d8ef86954fbdcef62c70470e.
