### ISSUE TITLE
I have to press back or close buttons more than once to exit widgetspace

### ISSUE THREAD

**Issue by beriain** [F4uzan/HgLauncher#35]
**What's the issue?**
I have to press back or close buttons more than once to exit widgetspace

**To reproduce…**
Steps to reproduce the behaviour:
1. Enter the widgetspace with double tap gesture
2. Open the widgetspace
3. Press the back button or the close button

**Expected behaviour**
Exit the widgetspace

**What did you see instead?**
The widgets blink but the screen keeps showing the widgetspace with them

**Device information (please complete the following information):**

 - Device: LG K10 2017
 - OS: Android 7.0
 - Hg version: 1.4.2
 - Are you running an official release from Play Store/GitHub Releases? Yes
![file](https://user-images.githubusercontent.com/7469634/57083573-0fd84900-6cf9-11e9-8c2d-6709f8b928c8.gif)

**Comment by F4uzan** [comment]
This is a fault in the gesture listener, and has been fixed in a1326e8ef5c5881aad59c47c2221a18b7916de08 (which thankfully only occur in double tap gesture). Thanks for the report!
