### ISSUE TITLE
resize widget in widgetspace

### ISSUE THREAD

**Issue by giupardeb** [F4uzan/HgLauncher#37]
Hello everybody! I can't resize any widget that are inside a widget space. I believe that this is a important feature.
Thank you for your awesome work!

**Comment by F4uzan** [comment]
Widgets can't be resized as of now. I plan to implement this in later builds where Widgetspace is further improved — stay tuned for that!

**Comment by giupardeb** [comment]
that's okay!

**Comment by F4uzan** [comment]
I'll be closing this issue as the feature to resize widgets have been implemented in v1.5.0.
