### ISSUE TITLE
Request: clear button for search bar

### ISSUE THREAD

**Issue by macdonaldster** [F4uzan/HgLauncher#38]
I have the app search auto open when I am going to the home screen from an app. The problem is the last search is still present. Sometimes this is desired but if not, I have to delete the text from the search box. 

I think have a little x button on the left of the search to clear it would be a simple but very impactful UI improvement. 

Thank you

**Comment by F4uzan** [comment]
Currently, persisting search text considered an issue (which has been sorted out by b70f4de74fb7c091535f9b50d25c8c343413ff9f). However, I'll consider the implementation of a clear button in a future release.

**Comment by macdonaldster** [comment]
Hi, I consider the search persisting as a "feature" :) (users, what are you going to do!)

Might might sense as an option or a quick pick list of previous searches when you start typing. 

Considering the change is there to wipe the search, I'll be fine living with it. :) Thanks for taking the time to review my issue.

**Comment by macdonaldster** [comment]
Sorry, closed by accident :)

**Comment by F4uzan** [comment]
Search history is also one of the things I'm considering. In all honesty, it has been put in hold for far too long — though this was mostly because I haven't found a feasible means to integrate it to the launcher.

I suppose maybe I now have a way to implement it, but we'll have to see later. I might end up adding an extra button in the far right of the search bar to host both clear all and history.

**Comment by macdonaldster** [comment]
Hi, I have a build with the following on my phone:
- button on left of search text bar to clear search 
- option in app list preferences to maintain search text when launcher is hidden/closed
- if option is "true", maintain search text on close/hide, etc.

I will run it tonight/tomorrow to make sure it is working correctly (my changes are pretty simple). If that works out I will do up a PR for consideration and review.

**Comment by macdonaldster** [comment]
Hi, I think I am good for a PR here but don't have permission to push my branch. I have only ever used Github in my own repository so not sure what needs to go on? 

I think I should probably figure out how language specific strings work, too, since I added some to the Preferences screen.

**Comment by F4uzan** [comment]
You might want to push your fork to GitHub first, then make a PR here. This should be all there's needed to have a reviewable PR.

The strings can be handled later, but if it's to your preference to merge them now, I wouldn't mind. I'll often handle most of them on my own when it isn't too much to do.

**Comment by macdonaldster** [comment]
Ok, I made a branch, not a fork. I'll make fork and merge my changes over
then try to create PR that way, thanks!

**Comment by macdonaldster** [comment]
OK, addressed in PR #40

Hope it looks OK. Thanks for considering this change.

**Comment by F4uzan** [comment]
I'll be closing this as it has been fully addressed by the recent commits.
