### ISSUE TITLE
Request: shortcut from app search to widget view

### ISSUE THREAD

**Issue by macdonaldster** [F4uzan/HgLauncher#39]
Hi, I have the app search auto open when I go to the home screen. From here to viewing widgets, I have to get back to a blank home screen as then do the gesture to view the widgets.

I think it might be an improvement to have a permanent shortcut to widgets from the left of the search bar. 

Some people might find this annoying so it could be a good optional feature. 

Another possibility is to allow a right or left swipe to take you between widget app search (and vice versa).

Thanks!

**Comment by F4uzan** [comment]
I do have some uncertain plans regarding a type of shortcut for users to navigate better without leaving the search bar. The favourites panel might be reused for this, but I'm still reconsidering the positioning for such shortcuts.

That being said, I agree that it can be a bit annoying for users with the 'keep app list' option enabled — as the launcher seems to be more lenient towards the use of the desktop. We'll see what I can do to improve the usability in general.

Thanks for the report!

**Comment by macdonaldster** [comment]
out of curiosity, what IDE are you doing dev in? I am a programmer (VS 2019,C#, web stuff) and could take a crack at a PR (Can't promise anything, very little time outside of work)

**Comment by F4uzan** [comment]
As you have found, I'm using Android Studio (the project uses Gradle-compatible structure, used in Android Studio). I'd be happy to have some extra hands around here, any help is appreciated.

**Comment by macdonaldster** [comment]
I managed last night to get the clear button working. I have also added a preference to "maintain search" through launcher open/close (in the commit you referenced, it is always removed, but I thought it might make sense to make it a preference). I am just doing some QA on that branch (will have to be outside working/family time so not sure when!). 

Once I am confident it is all working well, I can make a PR for your review. I think before I do, I would try to get the APK on my physical device (currently using an emulated Pixel 2, I have an A8 in reality). 

I would understand if the PR had to remove the preference setting and just have the simple "click to clear" functionality if you are trying to keep the preferences minimal, etc (no big deal!). I just wanted to learn how preferences are set and managed, etc. I could easily remove all of that based on a PR review.

Hopefully, I'll get something to you soon...

**Comment by F4uzan** [comment]
Sounds interesting! I'll be waiting for the PR. I think I wouldn't mind adding a preference to keep the search text, as it might come in handy for several users.

**Comment by macdonaldster** [comment]
RE: a shortcut to flip between search and widget space - have you considered a Floating Action Button? It might be doable (e.g. right above the search bar on right). I was thinking "hm, double click on search clear X button" but this seems like a hack and doesn't have a mirror on the Widgetspace side.

**Comment by F4uzan** [comment]
We can definitely make the clear search button work as a sort of 'do-it-all' button, able to be remapped by the user at will.

There should exist two states to the button: when there's text (active), and when the search bar is empty (idle); with this, we can have the user remap the idle state to do a certain action (like, say, opening Widgetspace or pulling up the app list).

I'm currently working on a Widgetspace redesign, so we can definitely make this work in tandem with that.

**Comment by macdonaldster** [comment]
If I got a chance to prototype this, you'd want a preference setting to
choose the "no text in search" alternate behavior, and then wire up the
click handler to do the selected behavior?

I could get a branch going with a couple of options (what you listed) and
then could fine tune once the basics made sense... I could hold off on PR
until widgetspace overhaul was done.

**Comment by F4uzan** [comment]
I suppose it is as you describe. We'll wire the idle state to a click listener. Alternatively, we can simply have a click listener that takes in the state of the search bar.

I think it's safe to get a PR going for the button. I'm still torn with how I'm going to redesign Widgetspace, and it may be put on hold due to that.

**Comment by macdonaldster** [comment]
OK, I will try to do this when I can (busy time right now) as this would be
a big feature for me (I could run the unreleased build as ... QA!).

**Comment by F4uzan** [comment]
Sure thing! I'll be working on it myself, seeing now that the launcher has a solid UX for the clear search button, I think extending what it does should be easy.

**Comment by macdonaldster** [comment]
OK, may the best PR win ha ha :)

I am new to collaborating in this way so please let me know if I am doing
something that doesn't make sense to you. Just want to help out.

**Comment by F4uzan** [comment]
No need to worry! The launcher's (and to an extent, its management) fairly lenient on what makes sense and what doesn't. In all honesty, I'm pretty glad anyone takes up their time to contribute; it makes the development one part more achieving than usual.

**Comment by macdonaldster** [comment]
OK, sounds great :) and just so you know, I am perfectly happy spending
time on something and getting feedback like "this doesn't work, going to
try a new solution" (it's no big deal, been programming a long time, not
every swing is a hit!). Please be honest in all feedback and I promise to
not get upset, ever. :)

**Comment by macdonaldster** [comment]
Sorry, one more thing - because of job/life I think I can get about 2 hours
a week on this outside of working hours but will do what I can, when I can.

**Comment by F4uzan** [comment]
That's perfectly fine! However, so as to not impede the launcher's next release, I'll put this feature request for a later version — it's mostly due to the fact that we would need the redesigned Widgetspace to accomplish what's targeted here, and waiting for that might take some time. Considering the big one month window since the last release, I suppose having more waits wouldn't be too great for the release cycle.

The next version will mostly be a maintenance release anyhow, there's no plan for a big feature unveiling, so we can have more time working on this as I get v1.4.2.2 ready.

So, please, take your time. We'll have some long months to work on this and Widgetspace.

**Comment by F4uzan** [comment]
The new widget-space UI should satisfy this request as a whole (not ad verbatim, however). Widget-space is now accessible by swiping to the left of the apps list.

I'll be closing this issue for now. Feel free to open a new request if the new UI still doesn't fulfill the request here.
