### ISSUE TITLE
Shorthand isn't picked up in search when you return to applist with search populated

### ISSUE THREAD

**Issue by macdonaldster** [F4uzan/HgLauncher#42]
When you return to the App List with text left in the search while it will filter apps correctly, it does not seem to include shorthand in the filter  (note: removed in recent release, but there is a PR in to include it again, maybe, with a user preference).

Steps to reproduce the behaviour:

1. if possible, set preference to preserve searches between App List hidden (e.g. app launched)
1. add shorthand to an app 
2. refresh (or otherwise ensure the shorthand is picked up)
3. launch the app
4. close app, returning to App List 
5. search (if enabled) will contain search text that should filter down to app w. shorthand but does not

Expected behaviour: the filter would pick up the shorthand text as well as application names.

**Comment by macdonaldster** [comment]
I can try to fix this.

A nice use case:

- you can set shorthand as "work" on a bunch of apps you use at work (e.g. Teams and Outlook)
- if you always keep "work" in your search bar all day at the office these apps are always there with no distractions

**Comment by F4uzan** [comment]
I suppose this is closely related to #41 as well? I'd imagine the fix to be not too far from #41 at least. As with that issue, a PR is wholeheartedly welcome. I want to try fixing this (and #41 to an extent) myself, but my hands are currently full at the moment.

**Comment by macdonaldster** [comment]
Yeah, just made two issues to keep them separated, could address in same PR.

**Comment by F4uzan** [comment]
Closing this as it should be fixed in v1.4.2.2. If it isn't, feel free to reopen it.
