### ISSUE TITLE
[concept/propsal] Widgetspace: add search for app

### ISSUE THREAD

**Issue by macdonaldster** [F4uzan/HgLauncher#46]
It occurred to me today that a nice way to avoid dealing with the switch between WidgetSpace (WS) and AppList (AL) might be to have a persistent search bar floating at the bottom of WS (pinned apps on top). This would let people naturally stay in either WS or AL mode depending on their preference (by which I mean "last selected view"). This would be pretty natural for most people, in my opinion. Not sure what happens to the "close" and "add" WS buttons but maybe a swipe in from side menu with a hint could be used there (hint could appear to right of search close button so it was fairly obvious it was there but was out of the way?).

Just brainstorming!

**Comment by F4uzan** [comment]
I think this goes in line with some plans I have for Widgetspace. The current view of Widgetspace is mostly hacked together, and I honestly don't like how it doesn't flow together with the rest of the launcher.

The redesign for Widgetspace must account for this. There shouldn't be a 'go elsewhere to access widget', as that heavily disrupts the flow of interaction.

**Comment by F4uzan** [comment]
The navigation described here has been partially implemented by v1.5.0. I'll be closing this as we don't use the old widget-space UI anymore.
