### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by fynngodau** [F4uzan/HgLauncher#47]
I'd like to work on a German translation, unless somebody else has already started doing so.

**Comment by fynngodau** [comment]
Anyhow, I started translating and will open a PR soon.

Question: was the "slow" in "A launcher for a slow day" (an absolutely lovely description by the way) meant like "unhurried" or rather "lazy"?

**Comment by F4uzan** [comment]
'Unhurried' would be what the sentence is referring to, but 'lazy' does have a similar tone (as in, 'a lazy summer day').

And I believe there hasn't been any German translation done. You're free to translate and shuttle a PR over, or use Weblate for a more dedicated platform — I'll accept either of the submission though.

**Comment by fynngodau** [comment]
I suppose it won't matter since somebody translated it in the F-Droid repo as "Bummel-Tag" (which doesn't sound nearly as great as the original). I would have chosen "gemächlich" or "träge".
