### ISSUE TITLE
Please add grid mode

### ISSUE THREAD

**Issue by cytergen** [F4uzan/HgLauncher#5]

**Comment by F4uzan** [comment]
It's an neat idea and I can see it working, but I do plan on keeping the list for a while. I'll consider it — though I'll take in any pull request for this if anyone's interested.

**Comment by F4uzan** [comment]
This has been implemented, at long last, in https://github.com/F4uzan/HgLauncher/commit/d5b5634ddb8b4a4d547749fedf9f7a3cbc909536. I'll be closing this issue for now.
