### ISSUE TITLE
Information about new translation WebLate

### ISSUE THREAD

**Issue by giupardeb** [F4uzan/HgLauncher#52]
Hi guys! I started to translate hglauncher in italian on weblate. How can I send a PR with these new translation?
Thanks!

**Comment by F4uzan** [comment]
Translations done through Weblate will be merged automatically should I have time to do it. You shouldn't need to do anything else for your translations to be merged though.

**Comment by F4uzan** [comment]
I'll be closing this issue as the new translations have been merged.
