### ISSUE TITLE
Icon packs don't apply

### ISSUE THREAD

**Issue by Rayzr522** [F4uzan/HgLauncher#53]
**What's the issue?**
I cannot use any icon packs with HgLauncher. 

**To reproduce…**
Steps to reproduce the behaviour:
1. Install an icon pack (I have tried several, but two examples are Delta icons and Frost icons)
2. Go to settings
3. Select the icon pack
4. Close settings
5. Open settings again

**Expected behaviour**
The icon pack applies and shows in the app list. 

**What did you see instead?**
It reverts to the default icon set. 

**Screenshots**
Not much to show, it lists the packs as available but selecting the icon pack doesn't persist. 

**Device information (please complete the following information):**
 - Device: S7
 - OS: Android 8.1
 - Hg version: 1.4.2.2
 - Are you running an official release from Play Store/GitHub Releases? No, from F-Droid

**Comment by F4uzan** [comment]
Icon pack works fine on my side. Are you running the Samsung stock ROM?

**Comment by PrivacyInvader** [comment]
Same issue for me with this crappy little:
ZTE Z3001S "extra" phone
Android 7.1.1. 
HG Launcher 1.4.2.2

Truly an awful device, this ZTE. The launcher helps a ton over the stock offering but I can't get icons working either. Tried Frost and Lines...the latter probably incompatible.

**Comment by F4uzan** [comment]
I'll definitely have a look at the issue. It seems like a few of my testers are reporting similar issues with the build — though I'm not sure if any of the recent commits have fixed the issue.

**Comment by Rayzr522** [comment]
Interesting, I'd love to hear what your tests come up with. And yes, I am
using the stock Samsung ROM for my S7. :)

**Comment by F4uzan** [comment]
It seems that the following commit addresses the issue, but I can't confirm this as an A/B test I did shows some device still having strange issues with icon packs,

https://github.com/F4uzan/HgLauncher/commit/04dae90d7cf069b2306633e7a0fd48627dbe0b67

This commit in question is not in any of the public releases of the launcher. However, if it's possible, I may try pushing a test build — should anyone be available to test it, of course.

**Comment by macdonaldster** [comment]
I am willing to test it. I can d/l and build this if you don't get a test build up soon (let me know if that is easier for you).

**Comment by Rayzr522** [comment]
I'd also be willing to test it, and if you'd be interested, I have a Jenkins instance that i could set the project up on so you could have live dev builds. If you're interested, I'd just need build instructions and I could get it all set up. But in the meantime, if you happen to get a test build out, I'd be happy to try it!

**Comment by F4uzan** [comment]
[app-release.zip](https://github.com/F4uzan/HgLauncher/files/3516876/app-release.zip)

Attached here is a test release. It's built with my sign key, therefore F-Droid release will be incompatible with it — I advise a backup before trying the build out.

The test release should have all of the present changes of the launcher (up until the time of this writing); this should also include the commit I linked before.

**Comment by Rayzr522** [comment]
Awesome, thanks! Tested and confirmed with both Frost and Delta icons -- it
works fine now.

**Comment by F4uzan** [comment]
I'll chalk it up as the commit fixing the issue well. I'll keep this open until v1.4.3 is up though, so do notify me in case more related issues come through.

**Comment by F4uzan** [comment]
Closing as this has been solved with v1.4.2.3.
