### ISSUE TITLE
Request: Support re-ordering favorites bar

### ISSUE THREAD

**Issue by zmingee** [F4uzan/HgLauncher#6]
The only way currently to "re-order" the favorites bar is to successively remove favorites, and then re-add them in the preferred order.

Requesting either support for manually re-ordering the favorites bar, or perhaps an option for it to be sorted alphabetically.

Love the app! Thank you for your work on it! I'm not familiar with Android development, so I may dig into this in my spare time.

**Comment by F4uzan** [comment]
I had this in the back burner, so it's nice to see a request for it. I've implemented it (albeit rather haphazardly for now), and it should allow manual re=ordering of the apps.

I appreciate the support, thank you!
