### ISSUE TITLE
cant unpin apps

### ISSUE THREAD

**Issue by esotericDisciple** [F4uzan/HgLauncher#67]
...that's the issue ive been having, that i meant when i made my last issue (#64)...theres no menu or anything when long_pressing any pinned app, just slide control for shuffling them...

**Comment by F4uzan** [comment]
This issue has been fixed in the RC builds (see: #25 and https://github.com/F4uzan/HgLauncher/commit/9aad7cf801281a002632cec74153c223b4154bce). If you are using Google Play Store, you may opt-in to the beta programme to test the RC builds.

**Comment by esotericDisciple** [comment]
Im using auroradroid...are the RC's in fdroid repos?

**Comment by F4uzan** [comment]
No, it's limited to the releases made in Google Play Store. If it's not too much trouble, I can send the APK here (but this requires uninstallation of the F-Droid release).

**Comment by esotericDisciple** [comment]
ok

**Comment by esotericDisciple** [comment]
i'll try the apk if you can upload it here...whats wrong with fdroid though?

**Comment by F4uzan** [comment]
F-Droid releases are signed by F-Droid's sign key, which is incompatible with my sign key. Android will complain if the same app is signed by a different key.

I have attached the test release here. If it is possible, can you check the issue regarding #57 too? It will be a great help to me, as #57 doesn't occur at all on my test devices.

[app-release.apk.zip](https://github.com/F4uzan/HgLauncher/files/5094937/app-release.apk.zip)

**Comment by esotericDisciple** [comment]
Thanks, this build appears to fix both issues...

**Comment by F4uzan** [comment]
I'll be closing this issue as it should be sorted in the latest v1.5.0.
