### ISSUE TITLE
Hidden apps won't hide from settings menu

### ISSUE THREAD

**Issue by esmoak** [F4uzan/HgLauncher#8]
I can hide apps from the app drawer, but when I checkmark them in settings, the checkmark disappears after hitting the back button then going to hidden apps setting again to see if the checkmark persisted. 

Also, the check boxes are really close to the scroll bar in the hidden apps menu which results in accidental scrolls. 

Overall, you built a great launcher. It's nice that you included searx. Great job.

**Comment by F4uzan** [comment]
That's interesting. I'll have a stab at fixing it, as it seems to be a lingering old issue I recognise.

One more thing, what version of Android are you currently running? I remember this issue happening in Android 4.1 — but I wouldn't hazard a guess here; it can probably occur in later versions as well.

**Comment by esmoak** [comment]
Apologies for not including it in my post.

HUAWEI device, Android 8.0

I'll mess with it some more and see if there is anything I can do to make it not happen. 

I just realized that unchecking a hidden app also doesn't work from the settings. The check mark reappears when I go back to the settings.

**Comment by F4uzan** [comment]
Haven't quite sure whether the commit fixes the issue. So, reopening for the time being.

**Comment by esmoak** [comment]
Awesome work. F-Droid version 1.3.6.1 fixes this. I'm going to close this issue.

Thanks so much.
