### ISSUE TITLE
[Feature Request] Dedicated Open to App Drawer

### ISSUE THREAD

**Issue by CriticalComposer** [F4uzan/HgLauncher#87]
The current function of assigning the App Drawer to a gesture will open the last used space -- either the Apps or the Widget Space. We have a dedicated Widget Space gesture so I'd like a dedicated App Drawer function.

**Comment by F4uzan** [comment]
This does make sense. I'll add this in the upcoming release (or actually make 'open app list' do what it is intended to do).

**Comment by F4uzan** [comment]
I'll be closing this issue as the feature has been added in v1.5.1.
