### ISSUE TITLE
[feature request] disable the "swipe down from top" gesture for "open app list"

### ISSUE THREAD

**Issue by frknltrk** [F4uzan/HgLauncher#91]
Swiping down from the top of the homescreen displays the -dropdown- app list. Seems like there is not such an option to disable this gesture. "swipe down" is only a *general* gesture option for the entire home screen. It is still possible to open up the dropdown app list even though this option is set to "None".
It'd be great to have an option to disable this behaviour completely.

**Comment by F4uzan** [comment]
I can confirm that the drawer does react to the swipe down still. This'll be fixed by the next released. Thanks for the report!

**Comment by frknltrk** [comment]
> I can confirm that the drawer does react to the swipe down still. This'll be fixed by the next released. Thanks for the report!

oh i thought it was intentional but not a bug.
i'm looking forward to see it is fixed.
thanks for your great efforts!
